In [19]:
import pandas as pd
import numpy as np
from pathlib import Path

In [20]:
# ------------------------------
# Paths
# ------------------------------
PROJECT_ROOT = Path.cwd().parent
DATA_PATH = PROJECT_ROOT / "Dataset" / "Res_dataset.csv"
OUTPUT_PATH = PROJECT_ROOT / "Dataset" / "cleaned_dataset.csv"

In [21]:
# ------------------------------
# Load Dataset
# ------------------------------
df = pd.read_csv(DATA_PATH)
print("Dataset Loaded Successfully.\n")

Dataset Loaded Successfully.

In [22]:
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [23]:
print("Shape of the dataset :", df.shape)

Shape of the dataset : (9551, 21)

In [24]:
df.columns.tolist()

['Restaurant ID',
 'Restaurant Name',
 'Country Code',
 'City',
 'Address',
 'Locality',
 'Locality Verbose',
 'Longitude',
 'Latitude',
 'Cuisines',
 'Average Cost for two',
 'Currency',
 'Has Table booking',
 'Has Online delivery',
 'Is delivering now',
 'Switch to order menu',
 'Price range',
 'Aggregate rating',
 'Rating color',
 'Rating text',
 'Votes']

In [25]:
print("\nDuplicate Rows:", df.duplicated().sum())
print("Duplicate Restaurant IDs:", df.duplicated(subset="Restaurant ID").sum())

Duplicate Rows: 0
Duplicate Restaurant IDs: 0

In [26]:
# Remove duplicate Restaurant IDs if any
df.drop_duplicates(subset="Restaurant ID", inplace=True)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [28]:
print("\nMissing Values:\n")
print(df.isnull().sum())

Missing Values:

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [29]:
# Fill missing Cuisines
df["Cuisines"] = df["Cuisines"].fillna("Unknown")

In [30]:
# ------------------------------
# Convert Yes/No Columns
# ------------------------------
yes_no_cols = [
    "Has Table booking",
    "Has Online delivery",
    "Is delivering now",
    "Switch to order menu"
]

df[yes_no_cols] = df[yes_no_cols].replace({"Yes": 1, "No": 0}).astype(int)

C:\Users\venut\AppData\Local\Temp\ipykernel_29276\912489621.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[yes_no_cols] = df[yes_no_cols].replace({"Yes": 1, "No": 0}).astype(int)

In [31]:
# ------------------------------
# Remove Constant Columns
# ------------------------------
constant_cols = [col for col in df.columns if df[col].nunique() == 1]
print("\nConstant Columns:", constant_cols)

df.drop(columns=constant_cols, inplace=True)

Constant Columns: ['Switch to order menu']

In [32]:
# ------------------------------
# Convert Categorical Numerical Columns
# ------------------------------
df["Country Code"] = df["Country Code"].astype("category")
df["Price range"] = df["Price range"].astype("category")

In [33]:
# ------------------------------
# Unique Value Analysis
# ------------------------------
print("\nUnique Value Counts:\n")
for col in df.columns:
    print(f"{col}: {df[col].nunique()}")

Unique Value Counts:

Restaurant ID: 9551
Restaurant Name: 7446
Country Code: 15
City: 141
Address: 8918
Locality: 1208
Locality Verbose: 1265
Longitude: 8120
Latitude: 8677
Cuisines: 1826
Average Cost for two: 140
Currency: 12
Has Table booking: 2
Has Online delivery: 2
Is delivering now: 2
Price range: 4
Aggregate rating: 33
Rating color: 6
Rating text: 6
Votes: 1012

In [34]:
# ------------------------------
# Target Variable Understanding
# ------------------------------
print("\nTarget Variable: Aggregate rating")
print("Min:", df["Aggregate rating"].min())
print("Max:", df["Aggregate rating"].max())
print("Mean:", df["Aggregate rating"].mean())
print("Median:", df["Aggregate rating"].median())

print("\nNumber of Restaurants with 0 Rating:",
      (df["Aggregate rating"] == 0).sum())

Target Variable: Aggregate rating
Min: 0.0
Max: 4.9
Mean: 2.6663700136111403
Median: 3.2

Number of Restaurants with 0 Rating: 2148

In [35]:
# Statistical Summary
df.describe()

,Restaurant ID,Longitude,Latitude,Average Cost for two,Has Table booking,Has Online delivery,Is delivering now,Aggregate rating,Votes
count,9.551000e+03,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000
mean,9.051128e+06,64.126574,25.854381,1199.210763,0.121244,0.256622,0.003560,2.666370,156.909748
std,8.791521e+06,41.467058,11.007935,16121.183073,0.326428,0.436792,0.059561,1.516378,430.169145
min,5.300000e+01,-157.948486,-41.330428,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.019625e+05,77.081343,28.478713,250.000000,0.000000,0.000000,0.000000,2.500000,5.000000
50%,6.004089e+06,77.191964,28.570469,400.000000,0.000000,0.000000,0.000000,3.200000,31.000000
75%,1.835229e+07,77.282006,28.642758,700.000000,0.000000,1.000000,0.000000,3.700000,131.000000
max,1.850065e+07,174.832089,55.976980,800000.000000,1.000000,1.000000,1.000000,4.900000,10934.000000

In [36]:
df.to_csv(OUTPUT_PATH, index = False)